!!python/object:argparse.Namespace
batch_size: 256
eval_dir: /Users/Leo/Documents/Research/Graph Neural Networks/edge-proposal-set/eval/default
feat_dim: 128
log_dir: logs
log_interval: 1000
lr: 0.0003
n_iter: 3000000
name: default
purge: false
train_ckpt_interval: 50000
train_dir: /Users/Leo/Documents/Research/Graph Neural Networks/edge-proposal-set/train/default
